version: "3.8"
services:
  postgres:
    container_name: postgres_container
    image: postgres:latest
    ports:
      - "5431"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: adminadmin
      POSTGRES_DB: bike-sharing
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
